[package]
name = "libconsensus"
version = "0.0.1"
authors = ["Samuel Marks <@SamuelMarks>",
	   "Maxim Zakharov <5158255+Maxime2@users.noreply.github.com>"]
edition = "2018"

[dependencies]
os_pipe = "0.8.0"
serde = "1.0.91"
serde_derive = "1.0.91"
